dist: bionic
sudo: required
language: generic


install:
  - travis_retry sudo apt-get update
  - travis_wait 30 sudo apt-get -y install -qq python3 python3-pip ldc dub
  - travis_wait 30 sudo pip3 install ninja

script:
  - git clone https://github.com/Rogni/meson.git meson -b debug_dub
  - dub fetch ddbc
  - dub build ddbc
  - dub list
  - ls /home/travis/.dub/packages/derelict-pq-2.2.0/derelict-pq/lib/
  - ls /home/travis/.dub/packages/derelict-util-2.0.6/derelict-util/lib/
  - DC=ldc2 python3 meson/meson.py build
  
