dist: bionic
sudo: required
language: generic


install:
  - travis_retry sudo apt-get update
  - travis_wait 30 sudo apt-get -y install -qq python3 python3-pip ldc dub
  - travis_wait 30 sudo pip3 install ninja

script:
  - git clone https://github.com/Rogni/meson.git meson -b debug_dub
  - dub fetch ddbc
  - dub build ddbc
  - dub list
  - find $HOME/.dub -name libDerelictPQ.a
  - find $HOME/.dub -name libDerelictUtil.a
  - find $HOME/.dub -name libvibe_core.a
  - DC=ldc2 python3 meson/meson.py build
  
